name: nutritious_meals
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-308.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter 

  cupertino_icons: ^1.0.2
  fluro: ^2.0.5
  flutter_svg: ^2.0.5
  dio: ^5.1.1
  fluttertoast: ^8.2.1
  flutter_secure_storage: ^8.0.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0   # MobX代码生成库，用来生成 .g.dart的库
  build_runner: ^2.4.3
  provider: ^6.0.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/loading.jpg
    - assets/images/bg.png
    - assets/images/iconPark-map-distance.png
    - assets/images/order1.png
    - assets/images/barcode.png
    - assets/images/special_food.png
    - assets/images/food1.png
    - assets/images/海贼王.png
    - assets/images/bread.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
